"""Alembic environment.

Two things the generated template does not do, both of which matter here:

1. It points ``target_metadata`` at ``None``, so ``alembic revision
   --autogenerate`` cheerfully produces an empty migration and you only notice
   when the tables are missing in production.
2. It builds a *synchronous* engine, which cannot drive the ``asyncpg`` URL the
   app uses.
"""

import asyncio
from logging.config import fileConfig

from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config

# Importing the registry is what populates Base.metadata. Without it every
# autogenerated migration is empty.
import src.models  # noqa: F401  (imported for its side effects)
from alembic import context
from src.core.config import env as settings
from src.core.db import Base

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# The URL lives in settings, not alembic.ini, so there is exactly one source of
# truth and no database password committed to a config file.
config.set_main_option("sqlalchemy.url", settings.DATABASE_URL)

target_metadata = Base.metadata


def _configure(connection: Connection) -> None:
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        # Detect column type changes, which Alembic ignores by default.
        compare_type=True,
        # Detect server-default changes too.
        compare_server_default=True,
    )


def run_migrations_offline() -> None:
    """Emit SQL to stdout without connecting - useful for reviewed DB changes."""
    context.configure(
        url=settings.DATABASE_URL,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
    )
    with context.begin_transaction():
        context.run_migrations()


def _run(connection: Connection) -> None:
    _configure(connection)
    with context.begin_transaction():
        context.run_migrations()


async def run_migrations_online() -> None:
    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        # NullPool: a migration is a short-lived one-off process; pooling adds
        # nothing and leaves connections open on exit.
        poolclass=pool.NullPool,
    )

    async with connectable.connect() as connection:
        await connection.run_sync(_run)

    await connectable.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    asyncio.run(run_migrations_online())
