/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Google Login
         * @description Exchanges a Google ID token for one of ours.
         *
         *     The token is verified against Google's published keys - never trusted
         *     because the client sent it, and never decoded without signature checking.
         */
        post: operations["google_login_auth_google_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Lets the client check whether a stored token is still valid on launch.
         */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scans/text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify Text Scan
         * @description OCR path: extract the fields with the LLM, then check the register.
         *
         *     Both steps happen in this one call so the device makes a single round trip.
         */
        post: operations["verify_text_scan_scans_text_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scans/barcode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify Barcode Scan
         * @description Barcode path: decode the payload, then check the register. No LLM.
         *
         *     The payload arrives undecoded on purpose - see ``BarcodeScanRequest``.
         */
        post: operations["verify_barcode_scan_scans_barcode_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scans/manual": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify Manual Entry
         * @description Typed or corrected details. Nothing to extract, only to look up.
         */
        post: operations["verify_manual_entry_scans_manual_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Scan History
         * @description The signed-in user's scans, newest first.
         *
         *     The user comes from the bearer token, never from the URL. Paginated because
         *     an unbounded list grows without limit and eventually times out the request.
         */
        get: operations["scan_history_scans_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness only: is the process up and serving?
         *
         *     Deliberately does not touch the database. A liveness probe that fails on a
         *     slow query gets the container killed during a database blip, turning a
         *     degradation into an outage.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness
         * @description Readiness: can this instance actually serve traffic?
         *
         *     This is the one a load balancer should use to decide whether to send
         *     requests here.
         */
        get: operations["readiness_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AuthResponse
         * @description What the client stores on a successful sign-in.
         *
         *     The original schema returned only the user and no token, so there was
         *     nothing to authenticate the next request with.
         */
        AuthResponse: {
            /** Token */
            token: string;
            /** Expiresin */
            expiresIn: number;
            user: components["schemas"]["UserOut"];
        };
        /**
         * BarcodeScanRequest
         * @description Barcode path: the payload arrives undecoded, on purpose.
         *
         *     The client decodes a copy for its on-screen hint, but the verdict is only
         *     trustworthy if the server derives the batch number itself - otherwise a
         *     modified client can name any batch it likes and be told it is safe.
         */
        BarcodeScanRequest: {
            /** Raw */
            raw: string;
            /**
             * Symbology
             * @default
             */
            symbology: string;
            location?: components["schemas"]["Coordinates"] | null;
            /**
             * Method
             * @default barcode
             * @constant
             */
            method: "barcode";
        };
        /** Coordinates */
        Coordinates: {
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
        };
        /**
         * GoogleLoginRequest
         * @description The ID token returned by Google Sign-In on the device.
         */
        GoogleLoginRequest: {
            /** Idtoken */
            idToken: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * ManualEntryRequest
         * @description Typed or corrected details. Nothing to extract, only to look up.
         */
        ManualEntryRequest: {
            fields: components["schemas"]["MedicineFields"];
            /**
             * Gtin
             * @default
             */
            gtin: string;
            /**
             * Serial
             * @default
             */
            serial: string;
            location?: components["schemas"]["Coordinates"] | null;
            /**
             * Method
             * @default manual
             * @enum {string}
             */
            method: "manual" | "ocr_corrected" | "barcode_corrected";
        };
        /**
         * MedicineFields
         * @description Mirrors `MedicineFields` in the client exactly.
         *
         *     Every field defaults to "" rather than being optional, so the client never
         *     has to null-check. An absent value and an empty value are the same thing
         *     here: "we do not know".
         */
        MedicineFields: {
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * Salt
             * @default
             */
            salt: string;
            /**
             * Batchnumber
             * @default
             */
            batchNumber: string;
            /**
             * Mfddate
             * @default
             */
            mfdDate: string;
            /**
             * Expdate
             * @default
             */
            expDate: string;
            /**
             * Dose
             * @default
             */
            dose: string;
        };
        /**
         * MedicineResult
         * @description The single response shape for every scan endpoint.
         */
        MedicineResult: {
            fields: components["schemas"]["MedicineFields"];
            status: components["schemas"]["VerificationStatus"];
            /** Title */
            title: string;
            /** Message */
            message: string;
            /**
             * Gtin
             * @default
             */
            gtin: string;
            /**
             * Serial
             * @default
             */
            serial: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /** Name */
            name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * ScanHistoryEntry
         * @description One row of the history list.
         */
        ScanHistoryEntry: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Dose
             * @default
             */
            dose: string;
            /** Batchnumber */
            batchNumber: string;
            /**
             * Scannedat
             * Format: date-time
             */
            scannedAt: string;
            status: components["schemas"]["VerificationStatus"];
        };
        /**
         * TextScanRequest
         * @description OCR path: the client sends recognised text, the server does the rest.
         */
        TextScanRequest: {
            /** Rawtext */
            rawText: string;
            location?: components["schemas"]["Coordinates"] | null;
            /**
             * Method
             * @default ocr
             * @enum {string}
             */
            method: "ocr" | "ocr_corrected";
        };
        /** UserOut */
        UserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VerificationStatus
         * @enum {string}
         */
        VerificationStatus: "safe" | "unsafe" | "unknown";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    google_login_auth_google_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    verify_text_scan_scans_text_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TextScanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MedicineResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_barcode_scan_scans_barcode_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BarcodeScanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MedicineResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_manual_entry_scans_manual_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualEntryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MedicineResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_history_scans_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanHistoryEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readiness_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
